# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.2
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Moves the Mind addon for Hex Casting, adding Carpetmod Fakeplayer interop.
display_name: Moves the Mind
github_repo: hex-movesthemind
github_user: abilliontrillionstars
java_package: io.github.abilliontrillionstars.movesthemind
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mod_version: 0.1.0
modid: movesthemind
